<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="28855" started-at="2019-08-30T16:59:42Z" finished-at="2019-08-30T17:00:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28855" started-at="2019-08-30T16:59:42Z" finished-at="2019-08-30T17:00:11Z">
      <class name="Browser.TestScript04_TestNG">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="setUp" is-config="true" duration-ms="5305" started-at="2019-08-30T16:59:43Z" finished-at="2019-08-30T16:59:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testcase4(java.lang.String, java.lang.String)[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="testcase4" duration-ms="1779" started-at="2019-08-30T16:59:48Z" data-provider="BankTestData" finished-at="2019-08-30T16:59:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr219136]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ujYvEbY]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="tearDown" is-config="true" duration-ms="2098" started-at="2019-08-30T16:59:50Z" finished-at="2019-08-30T16:59:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="setUp" is-config="true" duration-ms="4427" started-at="2019-08-30T16:59:52Z" finished-at="2019-08-30T16:59:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testcase4(java.lang.String, java.lang.String)[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="testcase4" duration-ms="990" started-at="2019-08-30T16:59:56Z" data-provider="BankTestData" finished-at="2019-08-30T16:59:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User or Password is invalid] but found [User or Password is not valid]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User or Password is invalid] but found [User or Password is not valid]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Browser.TestScript04_TestNG.testcase4(TestScript04_TestNG.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="tearDown" is-config="true" duration-ms="2260" started-at="2019-08-30T16:59:57Z" finished-at="2019-08-30T16:59:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="setUp" is-config="true" duration-ms="3767" started-at="2019-08-30T16:59:59Z" finished-at="2019-08-30T17:00:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testcase4(java.lang.String, java.lang.String)[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="testcase4" duration-ms="999" started-at="2019-08-30T17:00:03Z" data-provider="BankTestData" finished-at="2019-08-30T17:00:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User or Password is invalid] but found [User or Password is not valid]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User or Password is invalid] but found [User or Password is not valid]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Browser.TestScript04_TestNG.testcase4(TestScript04_TestNG.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="tearDown" is-config="true" duration-ms="257" started-at="2019-08-30T17:00:04Z" finished-at="2019-08-30T17:00:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="setUp" is-config="true" duration-ms="3910" started-at="2019-08-30T17:00:04Z" finished-at="2019-08-30T17:00:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testcase4(java.lang.String, java.lang.String)[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="testcase4" duration-ms="761" started-at="2019-08-30T17:00:08Z" data-provider="BankTestData" finished-at="2019-08-30T17:00:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User or Password is invalid] but found [User or Password is not valid]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User or Password is invalid] but found [User or Password is not valid]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Browser.TestScript04_TestNG.testcase4(TestScript04_TestNG.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Browser.TestScript04_TestNG@4501b7af]" name="tearDown" is-config="true" duration-ms="2112" started-at="2019-08-30T17:00:09Z" finished-at="2019-08-30T17:00:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Browser.TestScript04_TestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
